### ISSUE TITLE
What's up with the textures for the 1.12.2 version?

### ISSUE THREAD

**Issue by Calextrix** [Lance5057/Butchercraft#22]
I've been a fan of this mod for a while, but when I was making a new modpack when I went to test it all of the textures show as the default pink and black except for the butchers knife which has the cow carcass texture and the meat grinder which has the right model only when placed, as an item it has the pink and black texture, I've seen threads online about how you were working on it but it's been nearly 3-4 years since those, so wtf, I don't mean any hate or anything but this is a pretty large issue, every other version seems to work fine with the textures except 1.12.2, I even made a instance where it was just Butchercraft and it still had the texture issue, please please please fix this, this is one of my favorite mods but it doesn't work on the most popular Minecraft versions to mod.

**Comment by VulcanVet** [comment]
I think the issue is that items are registered differently in 1.12 than previous versions. The code is basically 1.11 still, hence all the errors. It needs a rewrite. I had a go a couple of years back but can't code in Java for beans and thus got nowhere. I don't think the author has had time to work on this mod for a long time which is a shame as I also love this mod.
